### ISSUE TITLE
(Development) - View Designer

### ISSUE THREAD

**Issue by iYonga** [Shetty073/Ets2AtsCustomRichPresence#2]
Thank you for developing this. I am new to Visual Studio but I can read and understand your code, hence, I want to edit it for my personal use.

Is there a way to edit the interface visually? I can't launch the View Designer in VS 2019. How did you do it?

**Comment by Shetty073** [comment]
You are welcome. I too used the Visual Studio 2019 designer for developing this tool. It was
working fine on my IDE. I have not used any external piece of software for
developing this tool.
Can you post a screenshot of your IDE where you are facing this issue?

**Comment by iYonga** [comment]
![image](https://user-images.githubusercontent.com/30579752/93883904-dc7dcc00-fcea-11ea-8973-55a7f363c5d2.png)

This. How do I view the window visually? So I can edit the buttons and stuff.

**Comment by Shetty073** [comment]
# You are opening the file in the wrong way

![screenshot](https://user-images.githubusercontent.com/30448930/93910719-1ec10080-fd1f-11ea-9e4b-2ec7fef54c84.jpg)

#### Open this xaml file only (not the files within it) in order to work with the designer.

**Comment by iYonga** [comment]
Oh thank you so much! It works. Sorry!!!
